# App specific
groupName: ""
email: ""

hetzner:
  apiKey: ""

# Custom values
cert-manager-webhook-hetzner:
  namespace: ix-cert-manager
  certManager:
    namespace: ix-cert-manager
    serviceAccountName: cert-manager-certmanager

namespace: ix-cert-manager

global:
  namespace: ix-cert-manager

# Copied over stuff starts here

image:
  repository: tccr.io/tccr/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:12e0f84947ee7fc11f552e065a46d5a2b4e27cfc6ded0f624fc948c3138fb9a9

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: false

portal:
  open:
    enabled: false

operator:
  register: false

metrics:
  main:
    enabled: false
    type: "podmonitor"
    endpoints:
      - port: main
        interval: 5s
        scrapeTimeout: 5s
        path: /
        honorLabels: false