groupName: ""
email: ""

hetzner:
  apiKey: ""

namespace: ix-cert-manager

global:
  namespace: ix-cert-manager

secret:
  hetzner-secret:
    enabled: true
    type: Opaque
    data:
      api-key: "{{ .Values.hetzner.apiKey | b64enc }}"

######

image:
  repository: tccr.io/tccr/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:12e0f84947ee7fc11f552e065a46d5a2b4e27cfc6ded0f624fc948c3138fb9a9

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: false

portal:
  open:
    enabled: false

operator:
  register: false

metrics:
  main:
    enabled: false
    type: "podmonitor"
    endpoints:
      - port: main
        interval: 5s
        scrapeTimeout: 5s
        path: /
        honorLabels: false

manifestManager:
  enabled: false